
import './globals.css'
import { Providers } from './redux/provider';
import { Inter } from 'next/font/google'
import Header from "@/components/Header";

export const metadata = {
  title: "Movie APP~",
  description: "Generated by create next app",
};
// If loading a variable font, you don't need to specify the font weight
/* const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
}) */


export default function RootLayout({
  children, 
}) {
  return (
    <html lang="en">
      <body>
      <Header />
      
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )

}



/* 
// app/layout.js
import { Provider } from 'react-redux'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
      <Provider>
       {children}
       </Provider>
    </body>
  </html>  )
} */